import requests
import re
import time

jquery_urls = [
"https://code.jquery.com/jquery-3.7.1.js",
"https://code.jquery.com/jquery-3.7.1.min.js",
"https://code.jquery.com/jquery-3.7.1.slim.js",
"https://code.jquery.com/jquery-3.7.1.slim.min.js",
"https://code.jquery.com/jquery-3.7.0.js",
"https://code.jquery.com/jquery-3.7.0.min.js",
"https://code.jquery.com/jquery-3.7.0.slim.js",
"https://code.jquery.com/jquery-3.7.0.slim.min.js",
"https://code.jquery.com/jquery-3.6.4.js",
"https://code.jquery.com/jquery-3.6.4.min.js",
"https://code.jquery.com/jquery-3.6.4.slim.js",
"https://code.jquery.com/jquery-3.6.4.slim.min.js",
"https://code.jquery.com/jquery-3.6.3.js",
"https://code.jquery.com/jquery-3.6.3.min.js",
"https://code.jquery.com/jquery-3.6.3.slim.js",
"https://code.jquery.com/jquery-3.6.3.slim.min.js",
"https://code.jquery.com/jquery-3.6.2.js",
"https://code.jquery.com/jquery-3.6.2.min.js",
"https://code.jquery.com/jquery-3.6.2.slim.js",
"https://code.jquery.com/jquery-3.6.2.slim.min.js",
"https://code.jquery.com/jquery-3.6.1.js",
"https://code.jquery.com/jquery-3.6.1.min.js",
"https://code.jquery.com/jquery-3.6.1.slim.js",
"https://code.jquery.com/jquery-3.6.1.slim.min.js",
"https://code.jquery.com/jquery-3.6.0.js",
"https://code.jquery.com/jquery-3.6.0.min.js",
"https://code.jquery.com/jquery-3.6.0.slim.js",
"https://code.jquery.com/jquery-3.6.0.slim.min.js",
"https://code.jquery.com/jquery-3.5.1.js",
"https://code.jquery.com/jquery-3.5.1.min.js",
"https://code.jquery.com/jquery-3.5.1.slim.js",
"https://code.jquery.com/jquery-3.5.1.slim.min.js",
"https://code.jquery.com/jquery-3.5.0.js",
"https://code.jquery.com/jquery-3.5.0.min.js",
"https://code.jquery.com/jquery-3.5.0.slim.js",
"https://code.jquery.com/jquery-3.5.0.slim.min.js",
"https://code.jquery.com/jquery-3.4.1.js",
"https://code.jquery.com/jquery-3.4.1.min.js",
"https://code.jquery.com/jquery-3.4.1.slim.js",
"https://code.jquery.com/jquery-3.4.1.slim.min.js",
"https://code.jquery.com/jquery-3.4.0.js",
"https://code.jquery.com/jquery-3.4.0.min.js",
"https://code.jquery.com/jquery-3.4.0.slim.js",
"https://code.jquery.com/jquery-3.4.0.slim.min.js",
"https://code.jquery.com/jquery-3.3.1.js",
"https://code.jquery.com/jquery-3.3.1.min.js",
"https://code.jquery.com/jquery-3.3.1.slim.js",
"https://code.jquery.com/jquery-3.3.1.slim.min.js",
"https://code.jquery.com/jquery-3.3.0.js",
"https://code.jquery.com/jquery-3.3.0.min.js",
"https://code.jquery.com/jquery-3.3.0.slim.js",
"https://code.jquery.com/jquery-3.3.0.slim.min.js",
"https://code.jquery.com/jquery-3.2.1.js",
"https://code.jquery.com/jquery-3.2.1.min.js",
"https://code.jquery.com/jquery-3.2.1.slim.js",
"https://code.jquery.com/jquery-3.2.1.slim.min.js",
"https://code.jquery.com/jquery-3.2.0.js",
"https://code.jquery.com/jquery-3.2.0.min.js",
"https://code.jquery.com/jquery-3.2.0.slim.js",
"https://code.jquery.com/jquery-3.2.0.slim.min.js",
"https://code.jquery.com/jquery-3.1.1.js",
"https://code.jquery.com/jquery-3.1.1.min.js",
"https://code.jquery.com/jquery-3.1.1.slim.js",
"https://code.jquery.com/jquery-3.1.1.slim.min.js",
"https://code.jquery.com/jquery-3.1.0.js",
"https://code.jquery.com/jquery-3.1.0.min.js",
"https://code.jquery.com/jquery-3.1.0.slim.js",
"https://code.jquery.com/jquery-3.1.0.slim.min.js",
"https://code.jquery.com/jquery-3.0.0.js",
"https://code.jquery.com/jquery-3.0.0.min.js",
"https://code.jquery.com/jquery-3.0.0.slim.js",
"https://code.jquery.com/jquery-3.0.0.slim.min.js",
"https://code.jquery.com/jquery-2.2.4.js",
"https://code.jquery.com/jquery-2.2.4.min.js",
"https://code.jquery.com/jquery-2.2.3.js",
"https://code.jquery.com/jquery-2.2.3.min.js",
"https://code.jquery.com/jquery-2.2.2.js",
"https://code.jquery.com/jquery-2.2.2.min.js",
"https://code.jquery.com/jquery-2.2.1.js",
"https://code.jquery.com/jquery-2.2.1.min.js",
"https://code.jquery.com/jquery-2.2.0.js",
"https://code.jquery.com/jquery-2.2.0.min.js",
"https://code.jquery.com/jquery-2.1.4.js",
"https://code.jquery.com/jquery-2.1.4.min.js",
"https://code.jquery.com/jquery-2.1.3.js",
"https://code.jquery.com/jquery-2.1.3.min.js",
"https://code.jquery.com/jquery-2.1.2.js",
"https://code.jquery.com/jquery-2.1.2.min.js",
"https://code.jquery.com/jquery-2.1.1.js",
"https://code.jquery.com/jquery-2.1.1.min.js",
"https://code.jquery.com/jquery-2.1.0.js",
"https://code.jquery.com/jquery-2.1.0.min.js",
"https://code.jquery.com/jquery-2.0.3.js",
"https://code.jquery.com/jquery-2.0.3.min.js",
"https://code.jquery.com/jquery-2.0.2.js",
"https://code.jquery.com/jquery-2.0.2.min.js",
"https://code.jquery.com/jquery-2.0.1.js",
"https://code.jquery.com/jquery-2.0.1.min.js",
"https://code.jquery.com/jquery-2.0.0.js",
"https://code.jquery.com/jquery-2.0.0.min.js",
"https://code.jquery.com/jquery-1.12.4.js",
"https://code.jquery.com/jquery-1.12.4.min.js",
"https://code.jquery.com/jquery-1.12.3.js",
"https://code.jquery.com/jquery-1.12.3.min.js",
"https://code.jquery.com/jquery-1.12.2.js",
"https://code.jquery.com/jquery-1.12.2.min.js",
"https://code.jquery.com/jquery-1.12.1.js",
"https://code.jquery.com/jquery-1.12.1.min.js",
"https://code.jquery.com/jquery-1.12.0.js",
"https://code.jquery.com/jquery-1.12.0.min.js",
"https://code.jquery.com/jquery-1.11.3.js",
"https://code.jquery.com/jquery-1.11.3.min.js",
"https://code.jquery.com/jquery-1.11.2.js",
"https://code.jquery.com/jquery-1.11.2.min.js",
"https://code.jquery.com/jquery-1.11.1.js",
"https://code.jquery.com/jquery-1.11.1.min.js",
"https://code.jquery.com/jquery-1.11.0.js",
"https://code.jquery.com/jquery-1.11.0.min.js",
"https://code.jquery.com/jquery-1.10.2.js",
"https://code.jquery.com/jquery-1.10.2.min.js",
"https://code.jquery.com/jquery-1.10.1.js",
"https://code.jquery.com/jquery-1.10.1.min.js",
"https://code.jquery.com/jquery-1.10.0.js",
"https://code.jquery.com/jquery-1.10.0.min.js",
"https://code.jquery.com/jquery-1.9.1.js",
"https://code.jquery.com/jquery-1.9.1.min.js",
"https://code.jquery.com/jquery-1.9.0.js",
"https://code.jquery.com/jquery-1.9.0.min.js",
"https://code.jquery.com/jquery-1.8.3.js",
"https://code.jquery.com/jquery-1.8.3.min.js",
"https://code.jquery.com/jquery-1.8.2.js",
"https://code.jquery.com/jquery-1.8.2.min.js",
"https://code.jquery.com/jquery-1.8.1.js",
"https://code.jquery.com/jquery-1.8.1.min.js",
"https://code.jquery.com/jquery-1.8.0.js",
"https://code.jquery.com/jquery-1.8.0.min.js",
"https://code.jquery.com/jquery-1.7.2.js",
"https://code.jquery.com/jquery-1.7.2.min.js",
"https://code.jquery.com/jquery-1.7.1.js",
"https://code.jquery.com/jquery-1.7.1.min.js",
"https://code.jquery.com/jquery-1.7.0.js",
"https://code.jquery.com/jquery-1.7.0.min.js",
"https://code.jquery.com/jquery-1.7.js",
"https://code.jquery.com/jquery-1.7.min.js",
"https://code.jquery.com/jquery-1.6.4.js",
"https://code.jquery.com/jquery-1.6.4.min.js",
"https://code.jquery.com/jquery-1.6.3.js",
"https://code.jquery.com/jquery-1.6.3.min.js",
"https://code.jquery.com/jquery-1.6.2.js",
"https://code.jquery.com/jquery-1.6.2.min.js",
"https://code.jquery.com/jquery-1.6.1.js",
"https://code.jquery.com/jquery-1.6.1.min.js",
"https://code.jquery.com/jquery-1.6.js",
"https://code.jquery.com/jquery-1.6.min.js",
"https://code.jquery.com/jquery-1.5.2.js",
"https://code.jquery.com/jquery-1.5.2.min.js",
"https://code.jquery.com/jquery-1.5.1.js",
"https://code.jquery.com/jquery-1.5.1.min.js",
"https://code.jquery.com/jquery-1.5.js",
"https://code.jquery.com/jquery-1.5.min.js",
"https://code.jquery.com/jquery-1.4.4.js",
"https://code.jquery.com/jquery-1.4.4.min.js",
"https://code.jquery.com/jquery-1.4.3.js",
"https://code.jquery.com/jquery-1.4.3.min.js",
"https://code.jquery.com/jquery-1.4.2.js",
"https://code.jquery.com/jquery-1.4.2.min.js",
"https://code.jquery.com/jquery-1.4.1.js",
"https://code.jquery.com/jquery-1.4.1.min.js",
"https://code.jquery.com/jquery-1.4.js",
"https://code.jquery.com/jquery-1.4.min.js",
"https://code.jquery.com/jquery-1.3.2.js",
"https://code.jquery.com/jquery-1.3.2.min.js",
"https://code.jquery.com/jquery-1.3.2.pack.js",
"https://code.jquery.com/jquery-1.3.1.js",
"https://code.jquery.com/jquery-1.3.1.min.js",
"https://code.jquery.com/jquery-1.3.1.pack.js",
"https://code.jquery.com/jquery-1.3.js",
"https://code.jquery.com/jquery-1.3.min.js",
"https://code.jquery.com/jquery-1.3.pack.js",
"https://code.jquery.com/jquery-1.2.6.js",
"https://code.jquery.com/jquery-1.2.6.min.js",
"https://code.jquery.com/jquery-1.2.6.pack.js",
"https://code.jquery.com/jquery-1.2.5.js",
"https://code.jquery.com/jquery-1.2.5.min.js",
"https://code.jquery.com/jquery-1.2.5.pack.js",
"https://code.jquery.com/jquery-1.2.4.js",
"https://code.jquery.com/jquery-1.2.4.min.js",
"https://code.jquery.com/jquery-1.2.4.pack.js",
"https://code.jquery.com/jquery-1.2.3.js",
"https://code.jquery.com/jquery-1.2.3.min.js",
"https://code.jquery.com/jquery-1.2.3.pack.js",
"https://code.jquery.com/jquery-1.2.2.js",
"https://code.jquery.com/jquery-1.2.2.min.js",
"https://code.jquery.com/jquery-1.2.2.pack.js",
"https://code.jquery.com/jquery-1.2.1.js",
"https://code.jquery.com/jquery-1.2.1.min.js",
"https://code.jquery.com/jquery-1.2.1.pack.js",
"https://code.jquery.com/jquery-1.2.js",
"https://code.jquery.com/jquery-1.2.min.js",
"https://code.jquery.com/jquery-1.2.pack.js",
"https://code.jquery.com/jquery-1.1.4.js",
"https://code.jquery.com/jquery-1.1.4.pack.js",
"https://code.jquery.com/jquery-1.1.3.js",
"https://code.jquery.com/jquery-1.1.3.pack.js",
"https://code.jquery.com/jquery-1.1.2.js",
"https://code.jquery.com/jquery-1.1.2.pack.js",
"https://code.jquery.com/jquery-1.1.1.js",
"https://code.jquery.com/jquery-1.1.1.pack.js",
"https://code.jquery.com/jquery-1.1.js",
"https://code.jquery.com/jquery-1.1.pack.js",
"https://code.jquery.com/jquery-1.0.4.js",
"https://code.jquery.com/jquery-1.0.4.pack.js",
"https://code.jquery.com/jquery-1.0.3.js",
"https://code.jquery.com/jquery-1.0.3.pack.js",
"https://code.jquery.com/jquery-1.0.2.js",
"https://code.jquery.com/jquery-1.0.2.pack.js",
"https://code.jquery.com/jquery-1.0.1.js",
"https://code.jquery.com/jquery-1.0.1.pack.js",
"https://code.jquery.com/jquery-1.0.js",
"https://code.jquery.com/jquery-1.0.pack.js",
"https://code.jquery.com/jquery-migrate-3.4.1.js",
"https://code.jquery.com/jquery-migrate-3.4.1.min.js",
"https://code.jquery.com/jquery-migrate-3.4.0.js",
"https://code.jquery.com/jquery-migrate-3.4.0.min.js",
"https://code.jquery.com/jquery-migrate-3.3.2.js",
"https://code.jquery.com/jquery-migrate-3.3.2.min.js",
"https://code.jquery.com/jquery-migrate-3.3.1.js",
"https://code.jquery.com/jquery-migrate-3.3.1.min.js",
"https://code.jquery.com/jquery-migrate-3.3.0.js",
"https://code.jquery.com/jquery-migrate-3.3.0.min.js",
"https://code.jquery.com/jquery-migrate-3.2.0.js",
"https://code.jquery.com/jquery-migrate-3.2.0.min.js",
"https://code.jquery.com/jquery-migrate-3.1.0.js",
"https://code.jquery.com/jquery-migrate-3.1.0.min.js",
"https://code.jquery.com/jquery-migrate-3.0.1.js",
"https://code.jquery.com/jquery-migrate-3.0.1.min.js",
"https://code.jquery.com/jquery-migrate-3.0.0.js",
"https://code.jquery.com/jquery-migrate-3.0.0.min.js",
"https://code.jquery.com/jquery-migrate-1.4.1.js",
"https://code.jquery.com/jquery-migrate-1.4.1.min.js",
"https://code.jquery.com/jquery-migrate-1.4.0.js",
"https://code.jquery.com/jquery-migrate-1.4.0.min.js",
"https://code.jquery.com/jquery-migrate-1.3.0.js",
"https://code.jquery.com/jquery-migrate-1.3.0.min.js",
"https://code.jquery.com/jquery-migrate-1.2.1.js",
"https://code.jquery.com/jquery-migrate-1.2.1.min.js",
"https://code.jquery.com/jquery-migrate-1.2.0.js",
"https://code.jquery.com/jquery-migrate-1.2.0.min.js",
"https://code.jquery.com/jquery-migrate-1.1.1.js",
"https://code.jquery.com/jquery-migrate-1.1.1.min.js",
"https://code.jquery.com/jquery-migrate-1.1.0.js",
"https://code.jquery.com/jquery-migrate-1.1.0.min.js",
"https://code.jquery.com/jquery-migrate-1.0.0.js",
"https://code.jquery.com/jquery-migrate-1.0.0.min.js"
]

def detect_jquery_type(url):
    try:
        # Make a GET request to fetch the JavaScript file from the URL
        response = requests.get(url)
        if response.status_code == 200:
            # Split the content into lines and take the first two lines
            lines = response.text.splitlines()
            first_two_lines = lines[:2]

            # Calculate the length of each line
            lengths = [len(line) for line in first_two_lines]
            version = None
            if lengths[0] < 5:
                index = first_two_lines[1].find("jQuery")
                if index != -1:
                    #find version 
                    pattern = r'v\d\.\d{1,2}\.\d'
                    version = re.findall(pattern, first_two_lines[1])
                    print(f'the version is {version}')
                    print("line 2")
                    print(first_two_lines[1])
                else:
                    version = re.findall(pattern, first_two_lines[0])
                    print(f'the version is {version}')
                    print("line 1")
                    print(first_two_lines[0])

            return lengths
        else:
            print(f"Failed to fetch URL. Status code: {response.status_code}")
    except requests.exceptions.RequestException as e:
        print(f"An error occurred: {e}")

# Example usage:
for url in jquery_urls:
    detect_jquery_type(url)
    time.sleep(2) 

'''url = "https://code.jquery.com/jquery-3.7.1.js"
lengths = detect_jquery_type(url)
if lengths:
    print(f"Length of the first line: {lengths[0]}")
    print(f"Length of the second line: {lengths[1]}")'''